name: Fetch JUP Price

# give the job permission to write repo contents (so it can push prices.csv)
permissions:
  contents: write

on:
  schedule:
    - cron: "*/3 * * * *"   # run every 3 minutes
  workflow_dispatch:         # allow manual runs from UI

jobs:
  fetch-price:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run fetch script
        run: node fetchJupPrice.js

      - name: Commit and push CSV (if changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add prices.csv
          git commit -m "Update JUP price data [skip ci]" || echo "No changes to commit"
          git push
